# Site settings
title: Syang's Blog
name: Syang's Blog # your name
email: 2528519467@qq.com # your email address
description: >
    A Simple Jekyll Blog Theme. # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: " https://Syang111.github.io/" # the base hostname & protocol for your site
twitter_username: # your Twitter username
github_username: Syang111
disqus_username: # your disqus username

google-analytics: # add it if you have one

skillstree: true # turn on or off the skills tree in about page

# Build settings
permalink: none
markdown: kramdown
